### ISSUE TITLE
Display time in fullscreen mode

### ISSUE THREAD

**Issue by ittipatken** [docchula/el-player#10] opened 2023-07-02 06:57 UTC

**Comment by keenthekeen** [comment] 2023-07-03 07:55
You mean you want a clock that shows the current local time, right?

In the web page (i.e. visit the site and press F11), or in the video player (after clicking full screen icon at the player)?

**Comment by ittipatken** [comment] 2023-07-03 11:02
Yes, the proposal is to display the current local time in the video player (the latter). Though, I do not have any good solutions for this yet.

**Comment by keenthekeen** [comment] 2023-08-01 15:58
Possible solution: https://github.com/videojs/videojs-overlay

User should be able to turn this feature on or off.

**Comment by ittipatken** [comment] 2023-08-03 21:28
I think a toggle switch and a keyboard shortcut might be enough.

**Comment by keenthekeen** [comment] 2023-08-14 18:33
![image](https://github.com/docchula/el-player/assets/5007387/f0a2f464-105f-46d7-80c6-3c8169a3992d)

Done. Hotkey is implemented at "T".
The clock shows whether playing full screen or not.

**Comment by keenthekeen** [comment] 2023-08-14 18:42
The clock shows "Loading" a bit too long. Looking into this later.

**Comment by ittipatken** [comment] 2023-08-15 10:27
https://github.com/docchula/el-player/blob/a27f4b67588eac3b790aa3aff9c64e6e70678b89/src/components/Player.vue#L221

There is a 2 seconds interval between DOM updates. Maybe consider removing it?

**Comment by ittipatken** [comment] 2023-08-15 10:43
Apologies for another question, is the sudden zoom-in effect when enabling the clock intentional?

**Comment by keenthekeen** [comment] 2023-08-15 16:02
The "zoom-in effect" is caused by the addition of text from these lines:
```
<p class="my-2 hidden md:block text-gray-400 dark:text-gray-300">
    <b>Hotkeys</b>&emsp; Space: Pause, ▲/▼: Volume, ◄/►: Seek, F:
    Fullscreen<span v-if="isClockEnabled">, T: Toggle clock</span>
</p>
```

The problem will be fixed by showing/hiding the text using opacity class, instead of v-if, so that the dimensions of the page content are not changed.

**Closed as completed** 2023-08-15 21:22 UTC
